defaults:
  - _self_
hydra :
  sweeper:
    params:
      embedder: 
        - basic_model,
        - nucleotidetransformer,
        - parnet





output_dir: ${hydra:runtime.cwd}/../output/localization/${embedder} #save the path at the task path 

wandb:
  project: BERTLocRNA
  name: benchmark_embedding

model:
  __target__: CustomizedModel #All embeddings should input to this model
  config:
    nb_classes: 9
    dim_attention: 80
    headnum: 3
    drop_flat: 0.25
    Att_regularizer_weight: 0.001
    fc_dim: 100
    normalizeatt: True
    attmod: smooth
    sharp_beta: 1
    activation: gelu
    activation_att: tanh
    attention: True
    RNA_dim: 4
    RNA_order: ["Y RNA", "lincRNA", "lncRNA", "mRNA", "miRNA", "ncRNA", "pseudo", "rRNA", "scRNA", "scaRNA", "snRNA", "snoRNA", "vRNA"]


data:
  __target__: BERTLocRNA.utils.embedding_generator.load_embedding.${embedder}
  ***args


