defaults:
  - _self_

hydra :
  mode: MULTIRUN
  sweeper:
    params:
      model: 
        base_model
      task:
        RNAlocalization
      embedder:
        nucleotidetransformer,
        parnet


model: base_model
task: RNAlocalization
embedder: parnet
batch_size: 8
compartments: ["Nucleus","Exosome","Cytosol","Cytoplasm","Ribosome","Membrane","Endoplasmic reticulum", "Microvesicle", "Mitochondrion"]
output_dir: ${hydra:runtime.cwd}/../output/${task}/${embedder} #save the path at the task path 


RNAlocalization:
  path: TerminatorJ/localization_multiRNA
wandb:
  project: BERTLocRNA
  name: benchmark_embedding


base_model:
  _target_: BERTLocRNA.models.base_model.CustomizedModel #All embeddings should input to this model
  config:
    nb_classes: 9
    dim_attention: 80
    headnum: 3
    drop_flat: 0.25
    Att_regularizer_weight: 0.001
    fc_dim: 100
    normalizeatt: True
    attmod: smooth
    sharp_beta: 1
    activation: gelu
    activation_att: tanh
    attention: True
    RNA_dim: 4
    RNA_order: ["UNK", "A", "C", "G", "T", "N", "Y RNA", "lincRNA", "lncRNA", "mRNA", "miRNA", "ncRNA", "pseudo", "rRNA", "scRNA", "scaRNA", "snRNA", "snoRNA", "vRNA"]

parnet:
  _target_: BERTLocRNA.utils.embedding_generator.ParnetEmbedder
  model_path: /home/sxr280/BERTLocRNA/RBPLLM/Parnet
  batch_size: ${batch_size}
  dataloader: true
nucleotidetransformer:
  _target_: BERTLocRNA.utils.embedding_generator.NucleotideTransformerEmbedder
  model_path: InstaDeepAI/nucleotide-transformer-2.5b-multi-species
  batch_size: ${batch_size}
  dataloader: true



Trainer:
  config:
    class_weights: None
    accelerator: gpu
    strategy: ddp
    max_epochs: 500
    precison: 32
    num_nodes: 1
    log_every_n_steps: 1000
    patience: 20
    output_dir: ${output_dir} 
    RNA_order: ${base_model.config.RNA_order}
    compartments: ${localizations}




