defaults:
  - launcher joblib
  - _self_
hydra : 
  mode : MULTIRUN
  sweeper:
    params:
      model:  
        - nucleotidetransformer
        - parnet
      task: 
        - RNAlocalization
      


batch_size: 2
RNAlocalization:
  path: TerminatorJ/localization_multiRNA


nucleotidetransformer:
  __target__: BERTLocRNA.utils.embedding_generator.NucleotideTransformerEmbedder
  model_path: InstaDeepAI/nucleotide-transformer-2.5b-multi-species


parnet:
  __target__: BERTLocRNA.utils.embedding_generator.ParnetEmbedder
  model_path: BERTLocRNA/RBPLLM/Parnet
