defaults:
 - _self_

hydra: 
  mode: MULTIRUN
  sweeper:
    params:
      embedder: nucleotidetransformer,
                parnet
             
      task:  RNAlocalization


embedder : nucleotidetransformer
task : RNAlocalization

RNAlocalization:
  path: TerminatorJ/localization_multiRNA

nucleotidetransformer:
  _target_: BERTLocRNA.utils.embedding_generator.NucleotideTransformerEmbedder
  model_path: InstaDeepAI/nucleotide-transformer-2.5b-multi-species
  batch_size: 2
  dataloader: false

parnet:
  _target_: BERTLocRNA.utils.embedding_generator.ParnetEmbedder
  model_path: /home/sxr280/BERTLocRNA/RBPLLM/Parnet
  batch_size: 50
  dataloader: false
  max_length: 8000

RNAFM:
  _target_: BERTLocRNA.utils.embedding_generator.RNAFMEmbedding
  model_path: /home/sxr280/BERTLocRNA/saved_model/RNAFM
  batch_size: 2
  dataloader: false
  max_length: 8000