defaults:
  - override hydra/launcher: joblib
  - _self_

hydra :
  mode: MULTIRUN
  sweeper:
    params:
      task:
        RNAembedding
        # RNAlocalization
      embedder:
        # DNABERT2,
        # RNAFM,
        # Parnet
        NT

task: RNAembedding
embedder: RNAFM

output_dir: /home/sxr280/BERTLocRNA/output/RNAlocalization/Figure
ref_path: /home/sxr280/BERTLocRNA/data/Train_fold0_utr_cds.csv
batch_size: 50
split: train
test: False
plot: True
machine: cpu

umap:
  _target_: BERTLocRNA.utils.visualization.UMAP_plot
  embedding: ${embedder}
  hidden_dim: ${${embedder}.hidden_dim}
  ref_path: ${ref_path}
  batch_size: ${batch_size}
  split: ${split}
  test: ${test}
  plot: ${plot}
  tokenization: ${${embedder}.tokenization}
  task: ${task}

Parnet:
  hidden_dim: 256
  tokenization: "one-hot"

RNAFM:
  hidden_dim: 640
  tokenization: "one-hot"
NT:
  hidden_dim: 2560
  tokenization: "6mer"

DNABERT2:
  hidden_dim: 768
  tokenization: "BPE"





